pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_token')   
        GITHUB_CREDENTIALS = credentials('github_credentials')  
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', credentialsId: 'github_credentials', url: 'https://github.com/rayenmaghraoui/mini-projet'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('devopsTP') {
                         bat 'docker build -t rayenmaghraoui/devopstp:latest .'
                    }
                   
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub_token') {
                        bat 'docker push rayenmaghraoui/devopstp:latest'
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    bat 'docker run -d -p 3000:3000 --name devopstp rayenmaghraoui/devopstp:latest'
                }
            }
        }
    }
}
